name: Run Sanitizers

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-03-08
          override: true
      - uses: davidB/rust-cargo-make@v1
        with:
          version: '0.30.0'
      - name: Sanitizers
        env:
          RUST_BACKTRACE: full
          RUST_LOG: 'trace'
        run: |
          tools/san_harness.sh
